export const navMenuList = [
  {
    data: {
      menus: [
        {
          id: 344,
          json: "https://static.msscdn.net/campaign_service/main/pan/v1/A/pan_344.json?1718241003000",
          title: "530데이",
          color: "#ED0060",
          isShowGlobalFilter: true,
          isCampaign: true,
          isNew: false,
          documentLocation: "https://www.musinsa.com/app/?menu_id=344",
          pageTitle: "무신사 스토어",
          pageID: "/main/campaign",
          panType: "campaign",
        },
        {
          id: 113,
          json: "https://main-service.musinsa.com/display/api/app/v1/main/pan/recommend?gf=A",
          title: "추천",
          color: "",
          isShowGlobalFilter: true,
          isCampaign: false,
          isNew: false,
          documentLocation: "https://www.musinsa.com/app/?menu_id=113",
          pageTitle: "무신사 스토어",
          pageID: "/main/home",
          panType: "recommend",
        },
        {
          id: 123,
          json: "https://display.musinsa.com/display/api/app/v2/main/pan/specialty/beauty?gf=A",
          title: "뷰티",
          color: "",
          isShowGlobalFilter: true,
          isCampaign: false,
          isNew: false,
          documentLocation: "https://www.musinsa.com/app/?menu_id=123",
          pageTitle: "무신사 스토어",
          pageID: "/main/beauty",
          panType: "beauty",
        },
        {
          id: 116,
          json: "https://ranking.musinsa.com/api/ranking/v1/pan/sections",
          title: "랭킹",
          color: "",
          isShowGlobalFilter: true,
          isCampaign: false,
          isNew: false,
          documentLocation: "https://www.musinsa.com/app/?menu_id=116",
          pageTitle: "무신사 스토어",
          pageID: "/main/ranking",
          panType: "ranking",
        },
        {
          id: 345,
          json: "https://main-service.musinsa.com/display/api/app/v1/main/pan/sale?gf=A",
          title: "세일",
          color: "",
          isShowGlobalFilter: true,
          isCampaign: false,
          isNew: false,
          documentLocation: "https://www.musinsa.com/app/?menu_id=345",
          pageTitle: "무신사 스토어",
          pageID: "/main/sale",
          panType: "sale",
          highlight: {
            lottieGray:
              "https://image.msscdn.net/display/images/main/sale_menu_lottie_gray.json?20240523",
            lottieRed:
              "https://image.msscdn.net/display/images/main/sale_menu_lottie_red.json?20240523",
            message: "매일 14시",
            endTime: 1718254800000,
          },
        },
        {
          id: 115,
          json: "https://static.msscdn.net/stylecontents/main/pan/v8/A/pan_115.json?1718241004000",
          title: "스타일",
          color: "",
          isShowGlobalFilter: true,
          isCampaign: false,
          isNew: false,
          documentLocation: "https://www.musinsa.com/app/?menu_id=115",
          pageTitle: "무신사 스토어",
          pageID: "/main/style",
          panType: "style",
        },
        {
          id: 121,
          json: "https://static.msscdn.net/campaign_service/main/pan/v1/A/pan_121.json?1718241002000",
          title: "이벤트",
          color: "",
          isShowGlobalFilter: true,
          isCampaign: false,
          isNew: false,
          documentLocation: "https://www.musinsa.com/app/?menu_id=121",
          pageTitle: "무신사 스토어",
          pageID: "/main/event",
          panType: "event",
        },
      ],
      selectedID: 113,
      mainID: 113,
      popupURL: "",
    },
  },
];
